# -*- coding: utf-8 -*-
"""Copy of Spatio-Temporal Rainfall Dynamics in Ethiopia (2000–2025)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KxI8dO5ImdxMYQZf5fS_1KZ-LxWSinoa
"""

# Spatio-Temporal Rainfall Dynamics in Ethiopia (2000–2025)
# Author: Wallelgn Melese
# Field: Climate Change Engineering

# Notes:
# - Uses CHIRPS v2.0 monthly rainfall
# - Focus is on national trends + spatial patterns
# - Built for climate risk interpretation, not just plotting

import os
import gzip
import shutil
import zipfile
import requests
from datetime import datetime

import numpy as np
import pandas as pd
import xarray as xr
import rioxarray
import geopandas as gpd
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec


# ---------------------------------------------------------------------------
# 1. BASIC SETUP
# ---------------------------------------------------------------------------

MONTHLY_DIR = "chirps_monthly_africa"
DAILY_DIR = "chirps_daily_africa"

for folder in [MONTHLY_DIR, DAILY_DIR]:
    os.makedirs(folder, exist_ok=True)

plt.rcParams.update({
    "figure.dpi": 300,
    "font.size": 12
})


# ---------------------------------------------------------------------------
# 2. ADMINISTRATIVE BOUNDARIES (ETHIOPIA)
# ---------------------------------------------------------------------------

def load_ethiopia_boundaries():
    """
    Download Ethiopia ADM0 (country) and ADM1 (regions).
    ADM0 is used for clipping, ADM1 only for visualization.
    """

    urls = {
        "adm0": "https://github.com/wmgeolab/geoBoundaries/raw/main/releaseData/gbOpen/ETH/ADM0/geoBoundaries-ETH-ADM0-all.zip",
        "adm1": "https://github.com/wmgeolab/geoBoundaries/raw/main/releaseData/gbOpen/ETH/ADM1/geoBoundaries-ETH-ADM1-all.zip"
    }

    def fetch(url, name):
        zip_path = f"{name}.zip"
        requests.get(url, stream=True).raise_for_status()

        with open(zip_path, "wb") as f:
            f.write(requests.get(url).content)

        with zipfile.ZipFile(zip_path) as z:
            z.extractall(name)

        shp = [os.path.join(name, f) for f in os.listdir(name) if f.endswith(".shp")][0]
        return gpd.read_file(shp).to_crs("EPSG:4326")

    adm0 = fetch(urls["adm0"], "eth_adm0").dissolve()
    adm1 = fetch(urls["adm1"], "eth_adm1")

    return adm0, adm1


# ---------------------------------------------------------------------------
# 3. CHIRPS DOWNLOAD HELPER
# ---------------------------------------------------------------------------

def download_chirps_monthly(year, month):
    """
    Download and unzip monthly CHIRPS raster if not already available.
    """
    fname = f"chirps-v2.0.{year}.{month:02d}.tif"
    gz_name = fname + ".gz"
    out_path = os.path.join(MONTHLY_DIR, fname)

    if os.path.exists(out_path):
        return out_path

    url = (
        "https://data.chc.ucsb.edu/products/CHIRPS-2.0/"
        f"africa_monthly/tifs/{gz_name}"
    )

    try:
        r = requests.get(url, timeout=15, stream=True)
        if r.status_code != 200:
            return None

        gz_path = os.path.join(MONTHLY_DIR, gz_name)
        with open(gz_path, "wb") as f:
            shutil.copyfileobj(r.raw, f)

        with gzip.open(gz_path, "rb") as fin, open(out_path, "wb") as fout:
            shutil.copyfileobj(fin, fout)

        os.remove(gz_path)
        return out_path

    except Exception:
        return None


# ---------------------------------------------------------------------------
# 4. MAIN PROCESSING
# ---------------------------------------------------------------------------

eth_boundary, eth_regions = load_ethiopia_boundaries()

monthly_stats = []
annual_rasters = []
available_years = []

print("Starting rainfall processing for Ethiopia (2000–2025)...")

for year in range(2000, 2026):

    monthly_layers = []

    for month in range(1, 13):
        tif = download_chirps_monthly(year, month)
        if tif is None:
            continue

        da = (
            rioxarray
            .open_rasterio(tif, masked=True)
            .squeeze()
            .rio.write_crs("EPSG:4326")
        )

        # CHIRPS sometimes includes negative fill values
        da = da.where(da >= 0)

        try:
            clipped = da.rio.clip(
                eth_boundary.geometry,
                eth_boundary.crs,
                drop=True
            )

            clipped = clipped.assign_coords(
                time=pd.to_datetime(f"{year}-{month:02d}-01")
            )

            monthly_stats.append({
                "date": clipped.time.values,
                "precip": float(clipped.mean())
            })

            monthly_layers.append(clipped)

        except Exception:
            continue

    if monthly_layers:
        annual_rasters.append(
            xr.concat(monthly_layers, dim="time").sum("time")
        )
        available_years.append(year)


df_monthly = (
    pd.DataFrame(monthly_stats)
    .set_index("date")
    .sort_index()
)


# ---------------------------------------------------------------------------
# 5. CLIMATOLOGY & ANOMALIES
# ---------------------------------------------------------------------------

# Use data up to 2024 to avoid incomplete-year bias
baseline = df_monthly[df_monthly.index.year <= 2024]

monthly_climatology = (
    baseline
    .groupby(baseline.index.month)["precip"]
    .mean()
)

df_monthly["anomaly"] = (
    df_monthly["precip"]
    - df_monthly.index.month.map(monthly_climatology)
)


# ---------------------------------------------------------------------------
# 6. VISUALIZATION DASHBOARD
# ---------------------------------------------------------------------------

fig = plt.figure(figsize=(24, 30))
gs = gridspec.GridSpec(4, 3, figure=fig, hspace=0.15, wspace=0.05)

# --- A. Time series of rainfall anomalies ---
ax_ts = fig.add_subplot(gs[0, :])

bar_colors = ["#1f77b4" if x >= 0 else "#d62728" for x in df_monthly["anomaly"]]

ax_ts.bar(
    df_monthly.index,
    df_monthly["anomaly"],
    color=bar_colors,
    width=20
)

ax_ts.set_title(
    "Rainfall Anomalies over Ethiopia (2000–2025)",
    fontsize=26,
    fontweight="bold"
)
ax_ts.set_ylabel("Rainfall anomaly (mm)", fontsize=18)
ax_ts.grid(alpha=0.3)


# --- B. Spatial snapshots ---
key_years = [2000, 2005, 2010, 2015, 2020, 2025]
positions = [(1,0), (1,1), (1,2), (2,0), (2,1), (2,2)]

vmax = max(float(r.max()) for r in annual_rasters)

for i, yr in enumerate(key_years):
    if yr not in available_years:
        continue

    ax = fig.add_subplot(gs[positions[i][0], positions[i][1]])
    idx = available_years.index(yr)

    im = annual_rasters[idx].plot(
        ax=ax,
        cmap="YlGnBu",
        vmin=0,
        vmax=vmax,
        add_colorbar=False
    )

    eth_regions.boundary.plot(ax=ax, linewidth=0.5, color="black")

    for _, reg in eth_regions.iterrows():
        ax.text(
            reg.geometry.centroid.x,
            reg.geometry.centroid.y,
            reg["shapeName"],
            fontsize=5,
            ha="center",
            clip_on=True
        )

    ax.set_title(f"Cumulative Rainfall – {yr}", fontsize=20, fontweight="bold")
    ax.axis("off")


# --- Colorbar ---
cax = fig.add_axes([0.2, 0.3, 0.6, 0.015])
cbar = fig.colorbar(im, cax=cax, orientation="horizontal")
cbar.set_label("Annual rainfall (mm)", fontsize=18, fontweight="bold")

plt.suptitle(
    "Spatio-Temporal Rainfall Variability in Ethiopia\n"
    "Climate Change Engineering Analysis – Wallelgn Melese",
    fontsize=32,
    fontweight="bold",
    y=0.98
)

plt.savefig("ethiopia_rainfall_analysis_github.png", bbox_inches="tight")
plt.show()

print("Done. Output saved as ethiopia_rainfall_analysis_github.png")